[tox]
envlist =
  py310-{linux,mac,win},
  py311-{linux,mac,win},
  py312-{linux,mac,win},
  py313-{linux,mac,win},
  py314-{linux,mac,win}

[gh-actions]
python =
  3.10: py310
  3.11: py311
  3.12: py312
  3.13: py313
  3.14: py314

[testenv]
platform =
  linux: linux
  mac: darwin
  win: win32

extras =
  dev

commands =
  linux: pytest {posargs}
  mac: pytest {posargs}
  win: pytest -m "not fails_on_windows" {posargs}
